<!DOCTYPE html>
<html>
<head>
    <title>地址管理</title>
    <meta charset="utf-8">
    <meta name="description" content="An Icon Font Generated By IcoMoon.io">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../assets/css/jquery.mobile-1.4.1.min.css"/>
    <link rel="stylesheet" href="../assets/css/style.css"/>
    <link rel="stylesheet" href="../assets/css/common.css"/>
    <script src="../assets/js/jquery-1.10.1.min.js"></script>
    <script src="../assets/js/jquery.mobile-1.4.1.min.js"></script>
</head>
<body>
<!--设置-->
<div data-role="page" id="ownedDetail">
    <div data-role="header" class="hd-theme-b">
        <h1>地址管理</h1>
        <a data-rel="back" class="ui-nodisc-icon ui-btn-left ui-btn  ui-btn-icon-notext" data-role="button">
            <span class="icon-arrow-left"></span>
        </a>
    </div>
    <div role="main" class="ui-content addressWrap">
        @foreach ($addresses as $row)
        <div class="item active">
            <div class="item-hd">
                <div class="username">{{$row->name}} <s class="red">{{$row->mobile}}</s></div>
                <p>{{$row->address}}</p>
                @if($row->rate == 100)
                <s class="icon-checkmark"></s>
                @endif
            </div>
            <div class="btn-menu">
                <a href="{{ URL::to('u/address/1/del') }}">删除</a>
                <a href="{{ URL::to('u/address/1/edit') }}">编辑</a>
                <a href="{{ URL::to('u/address/1/set') }}">设为默认地址</a>
            </div>
        </div>
        @endforeach
        <a class="btn-address" href="{{ URL::to('u/address/create') }}" data-transition="fade" >添加收货地址</a>
    </div>
</div>
</body>
</html>
