<!DOCTYPE html>
<html>
<head>
    <title>地址管理</title>
    <meta charset="utf-8">
    <meta name="description" content="An Icon Font Generated By IcoMoon.io">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?php echo asset('/assets/css/jquery.mobile-1.4.1.min.css');?>"/>
    <link rel="stylesheet" href="<?php echo asset('/assets/css/style.css');?>"/>
    <link rel="stylesheet" href="<?php echo asset('/assets/css/common.css');?>"/>

    <script src="<?php echo asset('assets/js/jquery-1.10.1.min.js');?>"></script>
    <script src="<?php echo asset('assets/js/jquery.mobile-1.4.1.min.js');?>"></script>
    <script src="<?php echo asset('assets/js/jquery.validate.min.js');?>"></script>
    <script src="<?php echo asset('assets/js/additional-methods.min.js');?>"></script>
    <script src="<?php echo asset('assets/js/common.js');?>"></script>
    <script src="<?php echo asset('assets/js/home/address.js');?>"></script>
    <script>
        $(document).on('vclick', '.update-address', function(){
            alert(11);
            $(".addForm").submit();
        });
    </script>
</head>
<body>
<!--添加地址-->
<div data-role="page" id="addAddress">
    <div data-role="header" class="hd-theme-b">
        <h1>编辑收货地址</h1>
        <a data-rel="back" class="ui-nodisc-icon ui-btn-left ui-btn  ui-btn-icon-notext" data-role="button">
            <span class="icon-arrow-left"></span>
        </a>
    </div>
    <div role="main" class="ui-content owned-detail">
        <form method="post" action="/u/address/5/edit" class="addForm">
            <label for="ftitle">收件人:</label>
            <input type="text" name="name" id="ftitle" class="text" placeholder="请输入收货人姓名" value="{{$address->name}}">
            <label for="phone">手机号码:</label>
            <input type="text" name="mobile" id="phone" class="text" placeholder="请输入收货人手机号码" value="{{$address->mobile}}">
            <label for="province">省份:</label>
            <input type="text" name="province" id="province" class="text" placeholder="请选择省份" value="{{$address->address[0]}}">
            <label for="city">城市:</label>
            <input type="text" name="city" id="city" class="text" placeholder="请选择城市" value="{{$address->address[1]}}">
            <label for="Region">地区:</label>
            <input type="text" name="county" id="Region" class="text" placeholder="请选择地区" value="{{$address->address[2]}}">
            <label for="address">详细地址:</label>
            <input type="text" name="address" id="address" class="text" placeholder="请填写街道地址" value="{{$address->address[3]}}">
            <label for="address">邮政编码:</label>
            <input type="text" name="postcode" id="address" class="text" placeholder="请填写邮编（非必要）" value="{{$address->postcode}}">
            <input type="checkbox" class="checkbox" name="rate" id="checkbox-0" data-mini="true" value="{{$address->rate}}" checked>
            <label for="checkbox-0">设为默认地址</label>
        </form>
    </div>
    <div data-role="footer" class="ui-footer ui-bar-inherit" role="contentinfo">
        <div class="pay-box"><a href="javascript:;" class="btn-pay-for ui-link update-address">保存</a></div>
    </div>
</div>
</body>
</html>
