<!DOCTYPE html>
<html>
<head>
    <title>地址管理</title>
    <meta charset="utf-8">
    <meta name="description" content="An Icon Font Generated By IcoMoon.io">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?php echo asset('/assets/css/jquery.mobile-1.4.1.min.css');?>"/>
    <link rel="stylesheet" href="<?php echo asset('/assets/css/style.css');?>"/>
    <link rel="stylesheet" href="<?php echo asset('/assets/css/common.css');?>"/>

    <script src="<?php echo asset('assets/js/jquery-1.10.1.min.js');?>"></script>
    <script src="<?php echo asset('assets/js/jquery.mobile-1.4.1.min.js');?>"></script>
    <script src="<?php echo asset('assets/js/jquery.validate.min.js');?>"></script>
    <script src="<?php echo asset('assets/js/additional-methods.min.js');?>"></script>
    <script src="<?php echo asset('assets/js/common.js');?>"></script>
    <script src="<?php echo asset('assets/js/home/address.js');?>"></script>

</head>
<body>
<!--添加地址-->
<div data-role="page" id="addAddress">
    <div data-role="header" class="hd-theme-b">
        <h1>添加收货地址</h1>
        <a data-rel="back" class="ui-nodisc-icon ui-btn-left ui-btn  ui-btn-icon-notext" data-role="button">
            <span class="icon-arrow-left"></span>
        </a>
    </div>
    <form method="post" action="" class="addForm">
        <div role="main" class="ui-content owned-detail">
            <label for="ftitle">收件人:</label>
            <input type="text" name="name" id="name" class="text" placeholder="请输入收货人姓名">
            <label for="phone">手机号码:</label>
            <input type="text" name="mobile" id="mobile" class="text" placeholder="请输入收货人手机号码">
            <label for="province">省份:</label>
            <input type="text" name="province" id="province" placeholder="请选择省份"
            data-rel="popup" data-position-to="window" class="text ui-btn ui-corner-all ui-shadow 
            ui-btn-inline ui-icon-check ui-btn-icon-left ui-btn-a" data-transition="pop"/>
            
            <div data-role="popup" id="province" data-theme="a" class="ui-corner-all">
                <form>
                    <div style="padding:10px 20px;">
                        <h3>Please sign in</h3>
                        <label for="un" class="ui-hidden-accessible">Username:</label>
                        <input type="text" name="user" id="un" value="" placeholder="username" data-theme="a">

                        <label for="pw" class="ui-hidden-accessible">Password:</label>
                        <input type="password" name="pass" id="pw" value="" placeholder="password" data-theme="a">

                        <button type="submit" class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-btn-icon-left ui-icon-check">Sign in</button>
                    </div>
                </form>
            </div>


            <label for="city">城市:</label>
            <input type="text" name="city" id="city" class="text" placeholder="请选择城市">
            <label for="Region">地区:</label>
            <input type="text" name="county" id="county" class="text" placeholder="请选择地区">
            <label for="address">详细地址:</label>
            <input type="text" name="address" id="address" class="text" placeholder="请填写街道地址">
            <label for="address">邮政编码:</label>
            <input type="text" name="postcode" id="postcode" class="text" placeholder="请填写邮编（非必要）">
            <input type="checkbox" class="checkbox" name="rate" id="checkbox-0" data-mini="true">
            <label for="checkbox-0">设为默认地址</label>
        </div>
    <div data-role="footer" class="ui-footer ui-bar-inherit" role="contentinfo">
        <div class="pay-box"><button data-role="submit" class="btn-pay-for ui-link add-address">保存</button></div>
    </div>
    </form>
</div>
</body>
</html>
