<!DOCTYPE html>
<html>
<head>
    <title>获得的商品</title>
    <meta charset="utf-8">
    <meta name="description" content="An Icon Font Generated By IcoMoon.io">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?php echo asset('/assets/css/jquery.mobile-1.4.1.min.css');?>"/>
    <link rel="stylesheet" href="<?php echo asset('/assets/css/style.css');?>"/>
    <link rel="stylesheet" href="<?php echo asset('/assets/css/common.css');?>"/>
    <link rel="stylesheet" href="<?php echo asset('/assets/css/jquery.mobile-1.4.0-rc.1.min.css');?>"/>
    <link rel="stylesheet" href="<?php echo asset('/assets/css/jquery.mobile.iscrollview.css');?>"/>
    <link rel="stylesheet" href="<?php echo asset('/assets/css/jquery.mobile.iscrollview-pull.css');?>"/>
    <link rel="stylesheet" href="<?php echo asset('/assets/css/demo.css');?>"/>

    <script src="<?php echo asset('assets/js/jquery-1.10.1.min.js');?>"></script>
    <script src="<?php echo asset('assets/js/jquery.mobile-1.4.1.min.js');?>"></script>

    <script src="<?php echo asset('assets/js/demo.js');?>"></script>
    <script src="<?php echo asset('assets/js/jquery.mobile-1.4.0-rc.1.min.js');?>"></script>
    <script src="<?php echo asset('assets/js/iscroll.js');?>"></script>
    <script src="<?php echo asset('assets/js/jquery.mobile.iscrollview.js');?>"></script>
    <script src="<?php echo asset('assets/js/pull-example.js');?>"></script>
    <script src="<?php echo asset('assets/js/home/userwins.js');?>"></script>
</head>
<body>
<!--侧滑菜单-->
<div data-role="page" id="home" class="pull-demo-page">
    <div data-role="header" class="">
        <h1>获得的商品</h1>
        <a href="" data-rel="back" class="ui-nodisc-icon ui-btn-left ui-btn  ui-btn-icon-notext" data-role="button">
            <span class="icon-arrow-left"></span>
        </a>
    </div>
    <div id="xp1" data-iscroll="" data-role="content">
        <div role="main" class="ui-content owned-list">
        
        </div>
        <div class="iscroll-pullup">
            <span class="iscroll-pull-icon"></span><span class="iscroll-pull-label" data-iscroll-loading-text="Custom loading text" data-iscroll-pulled-text="Custom pulled text">Custom reset text</span>
        </div>
    </div>
        
</div>
</body>
</html>
