<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="description" content="An Icon Font Generated By IcoMoon.io">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../assets/css/jquery.mobile-1.4.1.min.css"/>
    <link rel="stylesheet" href="../assets/css/style.css"/>
    <link rel="stylesheet" href="../assets/css/common.css"/>
    <script src="../assets/js/jquery-1.10.1.min.js"></script>
    <script src="../assets/js/jquery.mobile-1.4.1.min.js"></script>
</head>
<body>
<!--登录-->
<div data-role="page" id="login">
    <div data-role="header" class="hd-theme-b">
        <h1>登录</h1>
        <a href="" data-rel="back" class="ui-nodisc-icon ui-btn-left ui-btn  ui-btn-icon-notext" data-role="button">
            <span class="icon-arrow-left"></span>
        </a>
    </div>
    <div role="main" class="ui-content">
        <form action="api/signin" id="loginForm" class="loginForm" method="post">
            <div class="fieldcontain">
                <label for="name"></label>
                <input id="username" name="username" class="username" placeholder="请输入您的邮箱" type="text">
                <span class="icon-user icon-position"></span>
            </div>
            <div class="fieldcontain">
                <input id="password" name="password" class="password" value="" placeholder="请输入您密码" type="password">
                <span class="icon-key icon-position"></span>
            </div>
            <div data-role="controlgroup">
                <!--<a href="javascript:;" data-role="button" class="btn-theme-a submit">登录</a>-->
                <button data-role="submit" class="btn-theme-a submit">登录</button>
            </div>
        </form>
    </div>
    <div data-role="footer">
        <span class="inner-bar"><a href="">忘记密码</a><b>|</b><a href="signup" data-transition="slide">新用户注册</a></span>
        <div class="else-login">
            <div class="title">使用合作方账号登录</div>
            <ul>
                <li><a href="" class="sina"></a></li>
                <li><a href="" class="wx"></a></li>
                <li><a href="" class="qq"></a></li>
            </ul>
        </div>
    </div>
    <div class="tooltip">提示信息!</div>
</div>
</body>
</html>
