<!DOCTYPE html>
<html>
<head>
    <title>我的晒单</title>
    <meta charset="utf-8">
    <meta name="description" content="An Icon Font Generated By IcoMoon.io">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../assets/css/jquery.mobile-1.4.1.min.css"/>
    <link rel="stylesheet" href="../assets/css/style.css"/>
    <link rel="stylesheet" href="../assets/css/common.css"/>
    <script src="../assets/js/jquery-1.10.1.min.js"></script>
    <script src="../assets/js/jquery.mobile-1.4.1.min.js"></script>
</head>
<body>
<!--侧滑菜单-->
<div data-role="page">
    <div data-role="header" class="">
        <h1>我的晒单</h1>
        <a href="" data-rel="back" class="ui-nodisc-icon ui-btn-left ui-btn  ui-btn-icon-notext" data-role="button">
            <span class="icon-arrow-left"></span>
        </a>
    </div>
    <div role="main" class="ui-content bask-no">
        <div data-role="navbar" class="sort-bar ui-navbar" role="navigation">
            <ul>
                <li><a href="" class="ui-btn-active">已晒单(0)</a></li>
                <li><a href="" class="">未晒单(0)</a></li>
            </ul>
        </div>
        <div class="item">
            <div class="img-sm fl">
                    <span class="img-wide">
                        <a href="#"><img src="../assets/images/meinv.jpg" alt="美女"/></a>
                    </span>
            </div>
            <div class="info-wrap fr">
                <div class="title">苹果(Apple)iPhone 5C 16G 3G 手机</div>
                <div class="price">价值：00000.00</div>
                <div class="luckycode">幸运乐拍码:<s class="red">10000078</s></div>
                <div class="datetime">揭晓时间:2013-12-20 17:09</div>
                <div class="inner-wide">
                    <a href="#addBask" data-transition="fade" class="btn-pay fr">去晒单</a>
                </div>
            </div>
            <div class="arrow-right">
                <a href=""><span class="icon-uniE600"></span></a>
            </div>
        </div>
        <div class="noRecord">
            <span class="icon-spam"></span>暂时没有记录
        </div>
    </div>
</div>
<!--已晒单-->
<div data-role="page">
    <div data-role="header" class="">
        <h1>我的晒单</h1>
        <a href="" data-rel="back" class="ui-nodisc-icon ui-btn-left ui-btn  ui-btn-icon-notext" data-role="button">
            <span class="icon-arrow-left"></span>
        </a>
    </div>
    <div role="main" class="ui-content bask-list">
        <div data-role="navbar" class="sort-bar ui-navbar" role="navigation">
            <ul>
                <li><a href="" class="ui-btn-active">已晒单(0)</a></li>
                <li><a href="" class="">未晒单0)</a></li>
            </ul>
        </div>
        <div class="item">
            <div class="info-wrap fl">
                <div class="title">苹果(Apple)iPhone 5C 16G 3G 手机</div>
                <p style="font-size: 0.875em;color: #999999">第2期晒单  今天12.30</p>
                <div class="bask-content">
                    自Iphone和Android这两个牛逼的手机操作系统发布以来，在互联网界从此就多了一个新的名词-WebApp(意为基于WEB形式的应用程序，运行在高端的移动终端设备。
                    我相信各位童鞋应该和我一个样子，到处查找贴子，学习如何制作WebApp项目，经过我一番查找资料学习后准备分享给大
                </div>
                <div class="back-img">
                    <ul>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
            </div>
            <div class="arrow-right fl">
                <a href=""><span class="icon-uniE600"></span></a>
            </div>
        </div>
        <div class="noRecord">
            <span class="icon-spam"></span>暂时没有记录
        </div>
    </div>
</div>
</body>
</html>
